apiVersion: v1
kind: Service
metadata:
  name: rasa-service
  namespace: chatbot
spec:
  selector:
    app: rasa
  ports:
    - name: http
      protocol: TCP
      port: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: actions-service
  namespace: chatbot
spec:
  selector:
    app: actions
  ports:
    - name: http
      protocol: TCP
      port: 5055
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: chatbot
spec:
  selector:
    app: redis
  ports:
    - name: http
      protocol: TCP
      port: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rasa
  namespace: chatbot
  labels:
    app: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      namespace: chatbot
      labels:
        app: rasa
    spec:
      containers:
        - name: rasa
          image: localhost:5555/rasa
          imagePullPolicy: Always
          ports:
            - containerPort: 5005
          readinessProbe:
            httpGet:
              path: /
              port: 5005
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          envFrom:
            - secretRef:
                name: chatbot-config-secrets
            - configMapRef:
                name: chatbot-config-envs
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions
  namespace: chatbot
  labels:
    app: actions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions
  template:
    metadata:
      namespace: chatbot
      labels:
        app: actions
    spec:
      containers:
        - name: actions
          image: localhost:5555/actions
          imagePullPolicy: Always
          ports:
            - containerPort: 5055
          readinessProbe:
            httpGet:
              path: /health
              port: 5055
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
          envFrom:
            - secretRef:
                name: chatbot-config-secrets
            - configMapRef:
                name: chatbot-config-envs
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: chatbot
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      namespace: chatbot
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: bitnami/redis:6.0
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
          envFrom:
            - secretRef:
                name: chatbot-config-secrets
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chatbot-config-envs
  namespace: chatbot
data:
  ACTIONS_URL: http://actions-service
  REDIS_HOST: redis-service
---
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-config-secrets
  namespace: chatbot
type: Opaque
data:
  REDIS_PASSWORD: YmVzdHBhc3N3b3JkZXZlcgo=
